# Generated by Django 5.1.9 on 2025-06-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_file_origin_file_alter_file_md5_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('top_k', models.PositiveIntegerField(default=5)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Server-measured latency for the query (ms).', null=True)),
                ('result_count', models.PositiveIntegerField(blank=True, help_text='Number of hits returned to the client.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='document_se_user_id_f314f0_idx'), models.Index(fields=['created_at'], name='document_se_created_2ce8eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='VectorChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(help_text='Position of chunk in original text (0-based).')),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField(help_text='Dense vector (list[float])')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(help_text='Source document', on_delete=django.db.models.deletion.CASCADE, related_name='vector_chunks', to='core.file')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vector_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['file_id', 'chunk_index'],
                'indexes': [models.Index(fields=['user'], name='document_se_user_id_260fcc_idx'), models.Index(fields=['file'], name='document_se_file_id_4a330e_idx')],
                'unique_together': {('file', 'chunk_index')},
            },
        ),
    ]
