# Generated by Django 5.2.3 on 2025-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_search', '0002_searchquerylog_file_searchquerylog_result_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorchunk',
            name='chunk_hash',
            field=models.CharField(db_index=True, default=1, help_text='SHA256 hash of chunk_text for deduplication.', max_length=64),
            preserve_default=False,
        ),
    ]
