# Generated by Django 5.1.9 on 2025-05-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrfile',
            name='ocr_option',
            field=models.CharField(choices=[('Basic-ocr', 'Basic OCR'), ('Advanced-ocr', 'Advanced OCR')], db_index=True, default='Basic-ocr', max_length=20),
        ),
    ]
