# Generated by Django 5.1.9 on 2025-05-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ocr', '0002_ocrfile_ocr_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrfile',
            name='md5_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ocrrun',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], db_index=True, default='Pending', max_length=20),
        ),
    ]
