# Generated by Django 5.1.9 on 2025-05-17 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ocr', '0003_ocrfile_md5_hash_alter_ocrrun_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrfile',
            name='md5_hash',
        ),
        migrations.AlterField(
            model_name='ocrfile',
            name='ocr_option',
            field=models.CharField(blank=True, choices=[('Basic-ocr', 'Basic OCR'), ('Advanced-ocr', 'Advanced OCR')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ocrrun',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OCRBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_filepath', models.CharField(max_length=1024)),
                ('batch_status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Processing', max_length=20)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_batches', to='document_ocr.ocrfile')),
            ],
        ),
    ]
