# Generated by Django 5.1.9 on 2025-05-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_storage_run_storage_content_type_and_more'),
        ('document_ocr', '0004_remove_ocrfile_md5_hash_alter_ocrfile_ocr_option_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ocrfile',
            unique_together={('original_file', 'ocr_option')},
        ),
    ]
