# Generated by Django 5.1.8 on 2025-04-18 05:32

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointResponseTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint_name', models.CharField(db_index=True, max_length=255)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('filepath', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('md5_hash', models.CharField(blank=True, help_text='MD5 checksum for duplicate detection', max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=50)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('producer', models.CharField(blank=True, max_length=255, null=True)),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
                ('moddate', models.DateTimeField(blank=True, null=True)),
                ('trapped', models.CharField(blank=True, max_length=255, null=True)),
                ('encryption', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=255, null=True)),
                ('page_count', models.IntegerField(default=0, null=True)),
                ('is_encrypted', models.BooleanField(default=False, null=True)),
                ('pdf_version', models.CharField(blank=True, max_length=20, null=True)),
                ('fonts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('creator_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('creationdate_pdf', models.DateTimeField(blank=True, null=True)),
                ('moddate_pdf', models.DateTimeField(blank=True, null=True)),
                ('page_rotation', models.JSONField(blank=True, null=True)),
                ('custom_metadata', models.TextField(default=False, null=True)),
                ('metadata_stream', models.TextField(blank=True, null=True)),
                ('tagged', models.TextField(default=False, null=True)),
                ('userproperties', models.TextField(default=False, null=True)),
                ('suspects', models.TextField(default=False, null=True)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('javascript', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.JSONField(blank=True, null=True)),
                ('encrypted', models.BooleanField(default=False, null=True)),
                ('page_size', models.CharField(blank=True, max_length=255, null=True)),
                ('optimized', models.BooleanField(default=False, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('content_status', models.CharField(blank=True, max_length=255, null=True)),
                ('revision', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('pdfminer_info', models.JSONField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('md5_hash', models.CharField(blank=True, help_text='MD5 checksum for duplicate detection', max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processing', 'Processing'), ('Translating', 'Translating'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed')], db_index=True, default='Uploaded', max_length=50)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('characters', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('output_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(max_length=255)),
                ('secret_key', models.CharField(help_text='Used to sign messages for secure transmission', max_length=255)),
            ],
        ),
    ]
