# Generated by Django 5.2 on 2025-05-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='run',
        ),
        migrations.AddField(
            model_name='storage',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='storage',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
