# Generated by Django 5.1.9 on 2025-05-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_storage_run_storage_content_type_and_more'),
        ('grid_documents_interrogation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_files', to='grid_documents_interrogation.topic'),
        ),
    ]
