# Generated by Django 5.2.3 on 2025-06-20 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_file_topic'),
        ('grid_documents_interrogation', '0003_alter_databaseconnection_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='origin_file',
            field=models.ForeignKey(blank=True, help_text='Reference to the original file if this is a user-initiated copy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='core.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='md5_hash',
            field=models.CharField(blank=True, help_text='MD5 checksum for duplicate detection', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='md5_hash',
            field=models.CharField(blank=True, help_text='MD5 checksum for duplicate detection', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('user', 'md5_hash'), name='uniq_file_md5_per_user'),
        ),
    ]
