# Generated by Django 5.2.3 on 2025-07-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_file_origin_file_alter_file_md5_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True, help_text='Extracted plain text content of the file.', null=True),
        ),
    ]
