# Generated by Django 5.2.4 on 2025-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='document_type',
            field=models.CharField(blank=True, help_text='Predicted document type, e.g. Contract, Financial Report, etc.', max_length=255, null=True),
        ),
    ]
