# Generated by Django 6.0.6 on 2026-06-12 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_file_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('pe_classify', 'Classify Documents'), ('pe_extract_risk_clauses', 'Extract Risk Clauses'), ('pe_issue_spotting', 'Issue Spotting'), ('pe_findings_report', 'Findings Report'), ('ca_evidence_culling', 'Evidence Culling'), ('ca_pii_redaction', 'PII Redaction'), ('ca_extract_damages', 'Extract Damages'), ('ca_issue_tagging', 'Issue Tagging'), ('ca_duplicate_detection', 'Duplicate Detection'), ('le_analyze_communications', 'Analyze Communications'), ('le_wage_hour_analysis', 'Wage & Hour Analysis'), ('le_policy_comparison', 'Policy Comparison'), ('ip_analyze_patent', 'Patent Analysis'), ('ip_prior_art_search', 'Prior Art Search'), ('ip_infringement', 'Infringement Analysis'), ('rc_dsar_processing', 'DSAR Processing'), ('rc_redaction', 'Redaction'), ('rc_gap_analysis', 'Gap Analysis'), ('rc_policy_mapping', 'Policy Mapping'), ('ai_document_search', 'Semantic Document Search'), ('ai_document_classification', 'Document Classification'), ('ai_anonymization', 'Document Anonymization'), ('ai_ocr', 'OCR Text Extraction'), ('ai_translation', 'Document Translation'), ('ai_document_structure', 'Document Structure Analysis'), ('ai_redlining', 'Document Redlining'), ('ai_metadata_extraction', 'Metadata Extraction')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Partially_Completed', 'Partially Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=50)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('folder_id', models.UUIDField(blank=True, help_text='Process all files in this folder', null=True)),
                ('input_parameters', models.JSONField(blank=True, default=dict, help_text='Service-specific parameters')),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Summary of processing results')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of errors with file details')),
                ('celery_group_id', models.CharField(blank=True, help_text='Celery group ID for tracking', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkJobFileResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], db_index=True, default='Pending', max_length=50)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_results', to='core.bulkjob')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_results', to='core.file')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['bulk_job', 'status'], name='core_bulkjo_bulk_jo_4f13a8_idx'), models.Index(fields=['bulk_job', 'file'], name='core_bulkjo_bulk_jo_459a1c_idx')],
            },
        ),
    ]
