# Generated by Django 5.2.9 on 2025-12-21 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_litigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentanalysisrun',
            name='analysis_run_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this analysis run', unique=True),
        ),
    ]
