# Generated by Django 5.2.9 on 2025-12-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0001_initial'),
        ('ip_litigation', '0002_patentanalysisrun_analysis_run_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patentanalysisrun',
            unique_together={('case_name', 'client')},
        ),
    ]
