# Generated by Django 5.1.8 on 2025-04-18 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('ocr_option', models.CharField(choices=[('Basic-ocr', 'Basic OCR'), ('Advanced-ocr', 'Advanced OCR')], db_index=True, default='Basic-ocr', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCRFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocr_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('raw_docx_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('docx_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_versions', to='core.file')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_files', to='document_ocr.ocrrun')),
            ],
        ),
        migrations.CreateModel(
            name='OCRStorage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('ocr_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='document_ocr.ocrrun')),
            ],
        ),
    ]
