# Generated by Django 6.0.6 on 2026-06-11 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_file_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('filepath', models.CharField(max_length=1024)),
                ('file_hash', models.CharField(max_length=32)),
                ('change_summary', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_version_versions', to='core.file')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('file', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='VersionDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff_content', models.TextField()),
                ('diff_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_version_diffs', to='core.file')),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_diffs', to='document_versioning.documentversion')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_diffs', to='document_versioning.documentversion')),
            ],
        ),
    ]
