# Generated by Django 6.0.6 on 2026-06-11 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_file_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedliningRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedliningResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff_output_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('diff_html', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redlining_comparisons', to='core.file')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redlining_originals', to='core.file')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redlining_results', to='document_redlining.redliningrun')),
            ],
            options={
                'unique_together': {('original_file', 'comparison_file', 'run')},
            },
        ),
    ]
