# Generated by Django 5.2.3 on 2025-08-30 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_since', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_async', models.BooleanField(default=False)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_dash_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', '-generated_at'], name='home_dash_a_user_id_09d684_idx')],
            },
        ),
    ]
