# Generated by Django 5.2.9 on 2026-01-04 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_file_extension'),
        ('custom_authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('clustering_method', models.CharField(choices=[('agglomerative', 'Agglomerative Clustering'), ('dbscan', 'DBSCAN'), ('kmeans', 'K-Means'), ('spectral', 'Spectral Clustering')], db_index=True, default='agglomerative', max_length=50)),
                ('embedding_model', models.CharField(choices=[('bert-base-uncased', 'BERT Base Uncased'), ('roberta-base', 'RoBERTa Base'), ('legal-bert', 'Legal BERT')], default='bert-base-uncased', max_length=50)),
                ('generate_descriptions', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('optimal_clusters', models.IntegerField(default=0)),
                ('calinski_harabasz_index', models.FloatField(default=0.0)),
                ('davies_bouldin_index', models.FloatField(default=0.0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('media_duration', models.FloatField(default=0.0)),
                ('price', models.JSONField(default=dict)),
                ('elapsed_time', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustering_runs', to='custom_authentication.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustering_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_classification_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField()),
                ('cluster_label', models.CharField(blank=True, max_length=500, null=True)),
                ('file_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_results', to='document_classification.clusteringrun')),
            ],
            options={
                'db_table': 'document_classification_cluster_result',
                'ordering': ['cluster_id'],
            },
        ),
        migrations.CreateModel(
            name='ClusterFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filepath', models.CharField(max_length=1024)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('file_size', models.FloatField(default=0.0)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Unsupported', 'Unsupported File Type')], db_index=True, default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustering_results', to='core.file')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_files', to='document_classification.clusteringrun')),
                ('cluster_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='document_classification.clusterresult')),
            ],
            options={
                'db_table': 'document_classification_cluster_file',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='ClusterStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('embeddings_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('results_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='document_classification.clusteringrun')),
            ],
            options={
                'db_table': 'document_classification_storage',
            },
        ),
        migrations.AddIndex(
            model_name='clusteringrun',
            index=models.Index(fields=['client', '-created_at'], name='document_cl_client__152206_idx'),
        ),
        migrations.AddIndex(
            model_name='clusteringrun',
            index=models.Index(fields=['client', 'status'], name='document_cl_client__b00bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='clusteringrun',
            index=models.Index(fields=['project_id', 'service_id'], name='document_cl_project_282235_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clusterresult',
            unique_together={('run', 'cluster_id')},
        ),
    ]
