# Generated by Django 6.0.6 on 2026-06-13 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringrun',
            name='nb_cluster_method',
            field=models.CharField(choices=[('silhouette', 'Silhouette Score'), ('dendrogram', 'Dendrogram'), ('elbow', 'Elbow Method')], default='silhouette', max_length=20),
        ),
        migrations.AlterField(
            model_name='clusteringrun',
            name='clustering_method',
            field=models.CharField(choices=[('agglomerative', 'Agglomerative Clustering'), ('dbscan', 'DBSCAN'), ('optics', 'OPTICS'), ('kmeans', 'K-Means'), ('spectral', 'Spectral Clustering'), ('affinity_propagation', 'Affinity Propagation'), ('birch', 'BIRCH'), ('mean_shift', 'Mean Shift')], db_index=True, default='agglomerative', max_length=50),
        ),
        migrations.CreateModel(
            name='SubClusterRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_cluster_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('optimal_subclusters', models.IntegerField(default=0)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcluster_runs', to='document_classification.clusteringrun')),
            ],
            options={
                'db_table': 'document_classification_subcluster_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
