# Generated by Django 5.2.5 on 2025-08-31 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_file_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('core_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.file')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable key, e.g. 'welcome'.", max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('subject_template', models.TextField(help_text='Django template for subject')),
                ('body_text_template', models.TextField(blank=True, help_text='Plain-text template')),
                ('body_html_template', models.TextField(blank=True, help_text='HTML template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('to', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='Lower = sooner')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=190)),
                ('provider_id', models.CharField(blank=True, max_length=190)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, to='email_management.emailattachment')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='email_management.emailtemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('queued', 'Queued'), ('rendered', 'Rendered'), ('sending', 'Sending'), ('sent', 'Sent'), ('failure', 'Failure'), ('cancelled', 'Cancelled'), ('opened', 'Opened'), ('bounced', 'Bounced'), ('complained', 'Complained')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='email_management.outboxemail')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='outboxemail',
            index=models.Index(fields=['status', 'scheduled_at', 'priority'], name='email_manag_status_8e5edb_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxemail',
            index=models.Index(fields=['client_id'], name='email_manag_client__cbe468_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxemail',
            index=models.Index(fields=['user'], name='email_manag_user_id_a0464f_idx'),
        ),
    ]
