# Generated by Django 5.2.5 on 2025-08-31 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxemail',
            name='email_type',
            field=models.CharField(blank=True, choices=[('support_ticket_opened', 'Support: Ticket Opened'), ('support_ticket_updated', 'Support: Ticket Updated'), ('support_ticket_closed', 'Support: Ticket Closed'), ('info_announcement', 'Information / Announcement'), ('bug_report', 'Bug Report'), ('bug_fix_released', 'Bug Fix Released'), ('feature_request', 'Feature Request'), ('feature_shipped', 'Feature Shipped'), ('signup_welcome', 'Signup: Welcome'), ('signup_verification', 'Signup: Verification'), ('password_reset', 'Password Reset'), ('billing_invoice', 'Billing: Invoice'), ('billing_overage', 'Billing: Overage'), ('billing_payment_failed', 'Billing: Payment Failed'), ('security_alert', 'Security Alert'), ('weekly_digest', 'Weekly Digest'), ('custom', 'Custom')], db_index=True, default='', help_text='Optional classification for analytics/search.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='outboxemail',
            index=models.Index(fields=['email_type'], name='email_manag_email_t_31e2eb_idx'),
        ),
    ]
