# Generated by Django 5.2.5 on 2025-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_outboxemail_email_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxemail',
            name='email_type',
            field=models.CharField(choices=[('support_ticket_opened', 'Support: Ticket Opened'), ('support_ticket_updated', 'Support: Ticket Updated'), ('support_ticket_closed', 'Support: Ticket Closed'), ('info_announcement', 'Information / Announcement'), ('bug_report', 'Bug Report'), ('bug_fix_released', 'Bug Fix Released'), ('feature_request', 'Feature Request'), ('feature_shipped', 'Feature Shipped'), ('signup_welcome', 'Signup: Welcome'), ('signup_verification', 'Signup: Verification'), ('password_reset', 'Password Reset'), ('billing_invoice', 'Billing: Invoice'), ('billing_overage', 'Billing: Overage'), ('billing_payment_failed', 'Billing: Payment Failed'), ('security_alert', 'Security Alert'), ('weekly_digest', 'Weekly Digest'), ('custom', 'Custom')], db_index=True, default='custom', max_length=64),
        ),
    ]
