# Generated by Django 5.2.9 on 2025-12-17 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_file_extension'),
        ('custom_authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDiligenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(help_text='Name of the deal/transaction', max_length=255)),
                ('target_company', models.CharField(help_text='Target company name', max_length=255)),
                ('deal_type', models.CharField(choices=[('acquisition', 'Acquisition'), ('merger', 'Merger'), ('investment', 'Investment'), ('divestiture', 'Divestiture')], default='acquisition', max_length=50)),
                ('data_room_source', models.CharField(choices=[('google_drive', 'Google Drive'), ('sharepoint', 'SharePoint'), ('box', 'Box'), ('dropbox', 'Dropbox'), ('manual_upload', 'Manual Upload')], default='manual_upload', max_length=100)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_close_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_dd_runs', to='custom_authentication.client')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_diligence', to='core.run')),
            ],
            options={
                'db_table': 'private_equity_due_diligence_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('nda', 'Non-Disclosure Agreement'), ('supplier_contract', 'Supplier Contract'), ('employment_agreement', 'Employment Agreement'), ('lease_agreement', 'Lease Agreement'), ('ip_document', 'Intellectual Property Document'), ('privacy_policy', 'Privacy Policy'), ('financial_statement', 'Financial Statement'), ('audit_report', 'Audit Report'), ('insurance_policy', 'Insurance Policy'), ('regulatory_filing', 'Regulatory Filing'), ('other', 'Other')], max_length=100)),
                ('confidence_score', models.FloatField(help_text='AI confidence score (0.0 to 1.0)')),
                ('classification_metadata', models.JSONField(blank=True, default=dict, help_text='Additional classification details')),
                ('is_verified', models.BooleanField(default=False, help_text='Human verification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_doc_classifications', to='custom_authentication.client')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_classifications', to='core.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_document_classifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pe_verified_classifications', to=settings.AUTH_USER_MODEL)),
                ('due_diligence_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_classifications', to='private_equity.duediligencerun')),
            ],
            options={
                'db_table': 'private_equity_document_classification',
                'ordering': ['-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='DataRoomConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('sharepoint', 'SharePoint'), ('box', 'Box'), ('dropbox', 'Dropbox')], max_length=50)),
                ('connector_name', models.CharField(help_text='Human-readable name for this connector', max_length=255)),
                ('connection_config', models.JSONField(default=dict, help_text='Encrypted connection configuration')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('sync_error_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_data_room_connectors', to='custom_authentication.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_data_room_connectors', to=settings.AUTH_USER_MODEL)),
                ('due_diligence_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_room_connectors', to='private_equity.duediligencerun')),
            ],
            options={
                'db_table': 'private_equity_data_room_connector',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='Due Diligence Findings Report', max_length=255)),
                ('executive_summary', models.TextField(blank=True, help_text='Executive summary of findings')),
                ('document_summary', models.JSONField(default=dict, help_text='Summary of document types and counts')),
                ('risk_summary', models.JSONField(default=dict, help_text='Summary of risk clauses by type and level')),
                ('key_findings', models.JSONField(default=list, help_text='List of key findings')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommendations')),
                ('total_documents_reviewed', models.IntegerField(default=0)),
                ('total_risk_clauses_found', models.IntegerField(default=0)),
                ('high_risk_items_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_findings_reports', to='custom_authentication.client')),
                ('due_diligence_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings_reports', to='private_equity.duediligencerun')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pe_finalized_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_findings_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'private_equity_findings_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('change_of_control', 'Change of Control'), ('assignment', 'Assignment'), ('termination', 'Termination'), ('indemnity', 'Indemnity'), ('non_compete', 'Non-Compete'), ('data_privacy', 'Data Privacy'), ('force_majeure', 'Force Majeure'), ('liability_cap', 'Liability Cap'), ('governing_law', 'Governing Law'), ('dispute_resolution', 'Dispute Resolution')], max_length=100)),
                ('clause_text', models.TextField(help_text='Extracted clause text')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('page_number', models.IntegerField(help_text='Page number where clause was found')),
                ('position_start', models.IntegerField(blank=True, help_text='Character start position', null=True)),
                ('position_end', models.IntegerField(blank=True, help_text='Character end position', null=True)),
                ('risk_explanation', models.TextField(blank=True, help_text='Explanation of why this clause is risky')),
                ('mitigation_suggestions', models.TextField(blank=True, help_text='Suggested mitigation strategies')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_risk_clauses', to='custom_authentication.client')),
                ('due_diligence_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_clauses', to='private_equity.duediligencerun')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_risk_clauses', to='core.file')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pe_reviewed_clauses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_risk_clauses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'private_equity_risk_clause',
                'ordering': ['-risk_level', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('pe-create-dd-run', 'Create Due Diligence Run'), ('pe-classify-documents', 'Auto Classify & Dedup Documents'), ('pe-extract-risk-clauses', 'Clause & Obligation Extraction'), ('pe-generate-findings', 'Generate Findings Report'), ('pe-sync-data-room', 'Data Room Sync'), ('pe-document-structure', 'Document Structure Analysis'), ('pe-semantic-search', 'Investment Document Search'), ('pe-document-qa', 'Due Diligence Q&A'), ('pe-file-insights', 'Portfolio File Insights'), ('pe-project-summary', 'Deal Project Summary'), ('pe-document-anonymization', 'Confidential Deal Anonymization'), ('pe-ocr-financial', 'Financial Document OCR')], max_length=50)),
                ('service_name', models.CharField(help_text='Human-readable service name', max_length=255)),
                ('service_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('input_parameters', models.JSONField(default=dict, help_text='Service input parameters')),
                ('output_type', models.CharField(choices=[('document', 'Document'), ('pdf', 'PDF'), ('text', 'Text'), ('json', 'JSON Data'), ('data', 'Data File'), ('analytics', 'Analytics'), ('report', 'Report'), ('chart', 'Chart'), ('dashboard', 'Dashboard'), ('excel', 'Excel'), ('matrix', 'Matrix'), ('package', 'Package')], default='json', max_length=20)),
                ('output_count', models.IntegerField(default=0, help_text='Number of output files generated')),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('execution_metadata', models.JSONField(default=dict, help_text='Additional execution metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_service_executions', to='custom_authentication.client')),
                ('due_diligence_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_executions', to='private_equity.duediligencerun')),
                ('input_files', models.ManyToManyField(blank=True, related_name='pe_service_inputs', to='core.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_service_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'private_equity_service_execution',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_name', models.CharField(help_text='Name/title of the output', max_length=255)),
                ('output_type', models.CharField(choices=[('document', 'Document'), ('pdf', 'PDF'), ('text', 'Text'), ('json', 'JSON Data'), ('data', 'Data File'), ('analytics', 'Analytics'), ('report', 'Report'), ('chart', 'Chart'), ('dashboard', 'Dashboard'), ('excel', 'Excel'), ('matrix', 'Matrix'), ('package', 'Package')], max_length=20)),
                ('file_extension', models.CharField(blank=True, help_text='File extension if applicable', max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='pe_service_outputs/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('output_data', models.JSONField(blank=True, help_text='Structured data output', null=True)),
                ('output_text', models.TextField(blank=True, help_text='Text-based output')),
                ('download_url', models.URLField(blank=True, help_text='Direct download URL')),
                ('preview_url', models.URLField(blank=True, help_text='Preview URL')),
                ('output_metadata', models.JSONField(default=dict, help_text='Additional output metadata')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary output for the service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_service_outputs', to='custom_authentication.client')),
                ('service_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='private_equity.serviceexecution')),
            ],
            options={
                'db_table': 'private_equity_service_output',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='duediligencerun',
            index=models.Index(fields=['client', '-created_at'], name='private_equ_client__347a39_idx'),
        ),
        migrations.AddIndex(
            model_name='duediligencerun',
            index=models.Index(fields=['client', 'deal_name'], name='private_equ_client__3baa69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentclassification',
            unique_together={('file', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='dataroomconnector',
            unique_together={('user', 'due_diligence_run', 'connector_name')},
        ),
        migrations.AddIndex(
            model_name='serviceexecution',
            index=models.Index(fields=['user', 'service_type'], name='private_equ_user_id_2f3541_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceexecution',
            index=models.Index(fields=['due_diligence_run', 'status'], name='private_equ_due_dil_a9f74a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceexecution',
            index=models.Index(fields=['started_at'], name='private_equ_started_7fab9d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoutput',
            index=models.Index(fields=['service_execution', 'output_type'], name='private_equ_service_bb50f3_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoutput',
            index=models.Index(fields=['created_at'], name='private_equ_created_795259_idx'),
        ),
    ]
