# Generated by Django 5.1.8 on 2025-05-08 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('anonymization_type', models.CharField(choices=[('Presidio', 'Presidio-based Anonymization'), ('Spacy', 'Spacy-based Anonymization')], db_index=True, default='Presidio', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymizationStorage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('anonymized_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('deanonymized_storage_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='document_anonymizer.anonymizationrun')),
            ],
        ),
        migrations.CreateModel(
            name='DeAnonymize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unmasked_text', models.TextField(blank=True, null=True)),
                ('unmasked_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('presidio_masking_map', models.JSONField(blank=True, null=True)),
                ('spacy_masking_map', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deanonymized_versions', to='core.file')),
            ],
        ),
        migrations.CreateModel(
            name='Anonymize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('structured', 'Structured'), ('plain', 'Plain')], db_index=True, default='plain', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('anonymized_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('anonymized_html_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('entity_mapping_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('anonymized_markdown_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('anonymized_structured_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('anonymized_structured_txt_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('anonymized_structured_html_filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('presidio_masking_map', models.JSONField(blank=True, null=True)),
                ('spacy_masking_map', models.JSONField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('risk_breakdown', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymized_versions', to='core.file')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymized_files', to='document_anonymizer.anonymizationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('original_file', 'file_type'), name='unique_active_anonymize_per_file_type')],
            },
        ),
    ]
