# Generated by Django 5.2.4 on 2025-07-04 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_anonymizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizationStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('service_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('files_with_entities', models.PositiveIntegerField(default=0)),
                ('files_without_entities', models.PositiveIntegerField(default=0)),
                ('total_entities_anonymized', models.PositiveIntegerField(default=0)),
                ('entity_type_breakdown', models.JSONField(default=dict)),
            ],
        ),
    ]
