# Generated by Django 5.2.3 on 2025-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='autologin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='connector',
            field=models.CharField(choices=[('nextcloud', 'Nextcloud')], max_length=50),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='status',
            field=models.CharField(choices=[('created', 'User Created'), ('reset', 'Password Reset'), ('failed', 'Failed'), ('error', 'Error'), ('processing', 'Processing'), ('skipped', 'Skipped'), ('success', 'Success')], max_length=20),
        ),
    ]
