# Generated by Django 5.1.9 on 2025-05-30 19:36

import core.fields.encrypted_char
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid_documents_interrogation', '0002_topic_files_databaseconnection_topic_db_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=core.fields.encrypted_char.EncryptedCharField(max_length=255),
        ),
    ]
