# Generated by Django 5.2.5 on 2025-08-12 20:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('file_upload', 'File Upload'), ('file_edit', 'File Edit'), ('file_delete', 'File Delete'), ('translation', 'Translation'), ('comment', 'Comment'), ('approve', 'Approve'), ('anonymize', 'Anonymize'), ('copy', 'Copy'), ('redact', 'Redact'), ('open_document', 'Open Document'), ('write_document', 'Write Document'), ('other', 'Other')], db_index=True, max_length=50)),
                ('service_type', models.CharField(choices=[('payable', 'Payable'), ('non_payable', 'Non-Payable')], default='non_payable', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_event_logs', to='custom_authentication.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('other', 'Other')], default='card', max_length=50)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_payments', to='custom_authentication.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_status', models.CharField(db_index=True, default='inactive', max_length=50)),
                ('plan_code', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('elite', 'Elite')], default='starter', max_length=20)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('annual_prepay', models.BooleanField(default=False)),
                ('amount_billed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billing_cycle_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_cycle_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('tokens_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pages_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('translation_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('redact_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_subscriptions', to='custom_authentication.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tokens_used', models.PositiveIntegerField()),
                ('event_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='cost_centre.eventlog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_token_usage', to='custom_authentication.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_token_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_limit', models.PositiveBigIntegerField(default=0)),
                ('financial_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_budgets', to='custom_authentication.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user'], name='cc_budget_ten_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='cc_budget_user_tenant_unique'), models.CheckConstraint(condition=models.Q(('token_limit__gte', 0)), name='cc_budget_token_nonneg'), models.CheckConstraint(condition=models.Q(('financial_limit__gte', 0)), name='cc_budget_fin_nonneg')],
            },
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['user', 'tenant', '-created_at'], name='cc_evt_user_ten_ts'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type', '-created_at'], name='cc_evt_type_ts'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(('service_type', 'payable'), ('tokens_used', 0), _connector='OR'), name='cc_evt_tokens_zero_if_non_payable'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'tenant', 'idempotency_key'), name='cc_evt_user_tenant_idem_unique'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['tenant', '-payment_date'], name='cc_pay_ten_date'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['user', '-payment_date'], name='cc_pay_user_date'),
        ),
        migrations.AddConstraint(
            model_name='paymenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='cc_pay_amount_nonneg'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'user', '-updated_at'], name='cc_sub_ten_user_updated'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan_code'], name='cc_sub_plan'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('seat_count__gte', 1)), name='cc_sub_seats_ge_1'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['user', 'tenant', '-created_at'], name='cc_tok_user_ten_ts'),
        ),
    ]
