# Generated by Django 5.2.3 on 2025-06-28 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_file_origin_file_alter_file_md5_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStructureRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partition_strategy', models.CharField(choices=[('partition_pdf', 'partition_pdf'), ('partition_text', 'partition_text'), ('partition_auto', 'partition_auto')], default='partition_auto', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_runs', to='core.file')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_runs', to='core.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('coordinates', models.JSONField(blank=True, help_text='Bounding boxes, polygons, etc.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('embedding', models.JSONField(blank=True, help_text='Optional vector embedding of the element text.', null=True)),
                ('languages', models.JSONField(blank=True, help_text='List of language codes detected in this element.', null=True)),
                ('list_level', models.IntegerField(blank=True, help_text='Nesting level if this is a list item.', null=True)),
                ('list_item', models.CharField(blank=True, help_text='Bullet or number string of a list item.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='document_structures.documentelement')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='document_structures.documentstructurerun')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lexical_similarity', models.FloatField(blank=True, null=True)),
                ('semantic_similarity', models.FloatField(blank=True, null=True)),
                ('deviation_report', models.JSONField(blank=True, help_text='Detailed differences between sections, if computed.', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_first', to='document_structures.documentstructurerun')),
                ('run_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_second', to='document_structures.documentstructurerun')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('html', models.TextField(blank=True, help_text='HTML table representation.', null=True)),
                ('csv', models.TextField(blank=True, help_text='CSV table representation.', null=True)),
                ('json', models.JSONField(blank=True, help_text='JSON representation (e.g. rows/columns).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='document_structures.documentstructurerun')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTableCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_idx', models.IntegerField()),
                ('col_idx', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('rowspan', models.IntegerField(default=1)),
                ('colspan', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='document_structures.documenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SectionEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='document_structures.documentelement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_section_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='documentelement',
            index=models.Index(fields=['run', 'order'], name='document_st_run_id_841420_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttablecell',
            index=models.Index(fields=['table', 'row_idx', 'col_idx'], name='document_st_table_i_25f925_idx'),
        ),
    ]
