# Generated by Django 5.2.3 on 2025-06-29 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentElementPairComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(blank=True, max_length=100, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('lexical_similarity', models.FloatField(blank=True, null=True)),
                ('semantic_similarity', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_pairs', to='document_structures.documentcomparison')),
                ('element_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_element_1_in_comparisons', to='document_structures.documentelement')),
                ('element_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_element_2_in_comparisons', to='document_structures.documentelement')),
            ],
            options={
                'indexes': [models.Index(fields=['comparison', 'element_type'], name='document_st_compari_7e2333_idx')],
            },
        ),
    ]
