# Generated by Django 5.2.4 on 2025-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_operations', '0002_fileaccessentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileauditlog',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('renamed', 'Renamed'), ('downloaded', 'Downloaded'), ('shared', 'Shared'), ('unshared', 'Unshared'), ('trashed', 'Trashed'), ('restored', 'Restored'), ('version_restored', 'Version Restored'), ('public_link', 'Public Link Generated'), ('password_set', 'Password Protected'), ('previewed', 'Previewed'), ('access_updated', 'Access Level Updated')], max_length=50),
        ),
    ]
