# Generated by Django 5.2.4 on 2025-07-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_file_document_type'),
        ('document_operations', '0003_fileauditlog_extra_alter_fileauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolderlink',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_links', to='core.file'),
        ),
    ]
