# Generated by Django 6.0.5 on 2026-05-30 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_operations', '0005_userfilehide_userfolderhide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileColorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple'), ('grey', 'Grey'), ('yellow', 'Yellow')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_tag', to='document_operations.filefolderlink')),
            ],
        ),
        migrations.CreateModel(
            name='FolderColorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple'), ('grey', 'Grey'), ('yellow', 'Yellow')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_tag', to='document_operations.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FileAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='document_operations.filefolderlink')),
            ],
            options={
                'unique_together': {('file_link', 'alias_name')},
            },
        ),
        migrations.CreateModel(
            name='FolderAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='document_operations.folder')),
            ],
            options={
                'unique_together': {('folder', 'alias_name')},
            },
        ),
    ]
