# Generated by Django 5.1.9 on 2025-06-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_file_topic'),
        ('custom_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AI DocuMines', max_length=255)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10)),
                ('dark_mode', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('public_registration', models.BooleanField(default=True)),
                ('password_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('enforce_2fa', models.BooleanField(default=False)),
                ('email_verification', models.BooleanField(default=True)),
                ('api_rate_limit', models.PositiveIntegerField(default=60)),
                ('disable_file_downloads', models.BooleanField(default=False)),
                ('enable_gdpr_mode', models.BooleanField(default=True)),
                ('log_data_access', models.BooleanField(default=True)),
                ('redact_logs', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notify_enabled', models.BooleanField(default=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=512, null=True)),
                ('azure_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('slack_webhook', models.URLField(blank=True, null=True)),
                ('oauth_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_client_secret', models.CharField(blank=True, max_length=512, null=True)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('backup_retention', models.PositiveIntegerField(default=30)),
                ('encrypt_backups', models.BooleanField(default=True)),
                ('enable_logging', models.BooleanField(default=True)),
                ('log_retention', models.PositiveIntegerField(default=90)),
                ('log_level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('send_logs_to_admin', models.BooleanField(default=False)),
                ('default_role', models.CharField(default='User', max_length=50)),
                ('disable_self_delete', models.BooleanField(default=False)),
                ('max_users', models.PositiveIntegerField(default=100)),
                ('require_role_approval', models.BooleanField(default=True)),
                ('allow_file_upload', models.BooleanField(default=True)),
                ('max_upload_mb', models.PositiveIntegerField(default=100)),
                ('allowed_file_types', models.CharField(default='.pdf,.docx,.xlsx', max_length=255)),
                ('default_timezone', models.CharField(default='UTC', max_length=100)),
                ('enable_iso_logging', models.BooleanField(default=False)),
                ('enable_hipaa_mode', models.BooleanField(default=False)),
                ('enable_audit_log_download', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='custom_authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettingsAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_authentication.client')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.run')),
            ],
            options={
                'verbose_name': 'System Settings Audit Trail',
                'verbose_name_plural': 'System Settings Audit Trails',
                'ordering': ['-timestamp'],
            },
        ),
    ]
