# Generated by Django 5.2 on 2025-05-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationstorage',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_storages', to='document_translation.translationrun'),
        ),
    ]
