# Generated by Django 5.2.6 on 2025-10-03 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_file_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassClaimsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(help_text='Name of the class action case', max_length=255)),
                ('case_number', models.CharField(help_text='Court case number', max_length=100)),
                ('court_jurisdiction', models.CharField(blank=True, help_text='Court jurisdiction', max_length=255)),
                ('case_type', models.CharField(choices=[('consumer_protection', 'Consumer Protection'), ('securities', 'Securities'), ('antitrust', 'Antitrust'), ('employment', 'Employment'), ('data_breach', 'Data Breach'), ('product_liability', 'Product Liability'), ('environmental', 'Environmental'), ('other', 'Other')], default='consumer_protection', max_length=100)),
                ('claim_deadline', models.DateTimeField(help_text='Deadline for claim submissions')),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('intake', 'Intake Phase'), ('discovery', 'Discovery Phase'), ('settlement', 'Settlement Phase'), ('distribution', 'Distribution Phase'), ('closed', 'Closed')], default='intake', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mass_claims', to='core.run')),
            ],
            options={
                'db_table': 'class_actions_mass_claims_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('claimant_data', models.JSONField(default=dict, help_text='Flexible claimant form data')),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_score', models.FloatField(blank=True, help_text='Similarity score for duplicate detection', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Marked as Duplicate')], default='pending', max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='class_actions.intakeform')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_processed_forms', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_intake_forms', to=settings.AUTH_USER_MODEL)),
                ('mass_claims_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='class_actions.massclaimsrun')),
            ],
            options={
                'db_table': 'class_actions_intake_form',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(help_text='Name of the exhibit package', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the package contents')),
                ('bates_prefix', models.CharField(default='EXHIBIT', help_text='Bates number prefix', max_length=20)),
                ('bates_start', models.CharField(help_text='Starting Bates number', max_length=50)),
                ('bates_end', models.CharField(help_text='Ending Bates number', max_length=50)),
                ('total_pages', models.IntegerField(default=0, help_text='Total pages in package')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready for Production'), ('produced', 'Produced'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('production_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produced_at', models.DateTimeField(blank=True, null=True)),
                ('files', models.ManyToManyField(related_name='ca_exhibit_packages', to='core.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_exhibit_packages', to=settings.AUTH_USER_MODEL)),
                ('mass_claims_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_packages', to='class_actions.massclaimsrun')),
            ],
            options={
                'db_table': 'class_actions_exhibit_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('email', 'Email'), ('chat_log', 'Chat Log'), ('document', 'Document'), ('financial_record', 'Financial Record'), ('communication', 'Communication'), ('contract', 'Contract'), ('policy', 'Policy'), ('other', 'Other')], max_length=100)),
                ('is_culled', models.BooleanField(default=False, help_text='Whether document was culled (excluded)')),
                ('cull_reason', models.TextField(blank=True, help_text='Reason for culling')),
                ('relevance_score', models.FloatField(blank=True, help_text='AI-generated relevance score (0.0-1.0)', null=True)),
                ('contains_pii', models.BooleanField(default=False)),
                ('privilege_status', models.CharField(choices=[('none', 'No Privilege'), ('attorney_client', 'Attorney-Client'), ('work_product', 'Work Product'), ('other', 'Other Privilege')], default='none', max_length=50)),
                ('processing_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_evidence', to='core.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_evidence_documents', to=settings.AUTH_USER_MODEL)),
                ('mass_claims_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='class_actions.massclaimsrun')),
            ],
            options={
                'db_table': 'class_actions_evidence_document',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimantCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('mail', 'Physical Mail'), ('phone', 'Phone Call'), ('sms', 'SMS'), ('portal', 'Web Portal Message')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_content', models.TextField(blank=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_claimant_communications', to=settings.AUTH_USER_MODEL)),
                ('intake_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='class_actions.intakeform')),
                ('mass_claims_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimant_communications', to='class_actions.massclaimsrun')),
            ],
            options={
                'db_table': 'class_actions_claimant_communication',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PIIRedaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pii_type', models.CharField(choices=[('name', 'Personal Name'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('ssn', 'Social Security Number'), ('address', 'Physical Address'), ('credit_card', 'Credit Card Number'), ('bank_account', 'Bank Account Number'), ('driver_license', 'Driver License'), ('passport', 'Passport Number'), ('other', 'Other PII')], max_length=50)),
                ('original_text', models.TextField(help_text='Original text containing PII')),
                ('redacted_text', models.TextField(help_text='Text with PII redacted')),
                ('page_number', models.IntegerField(help_text='Page number where PII was found')),
                ('position_start', models.IntegerField(blank=True, null=True)),
                ('position_end', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(help_text='AI confidence in PII detection (0.0-1.0)')),
                ('is_verified', models.BooleanField(default=False, help_text='Human verification of redaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_pii_redactions', to='core.file')),
                ('mass_claims_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_redactions', to='class_actions.massclaimsrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_pii_redactions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_verified_redactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_actions_pii_redaction',
                'ordering': ['page_number', 'position_start'],
            },
        ),
        migrations.CreateModel(
            name='SettlementTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(choices=[('monetary', 'Monetary Settlement'), ('injunctive', 'Injunctive Relief'), ('mixed', 'Mixed Settlement'), ('other', 'Other')], default='monetary', max_length=50)),
                ('total_settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('attorney_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('administration_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_settlement_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notice_type', models.CharField(choices=[('publication', 'Publication Notice'), ('direct_mail', 'Direct Mail'), ('email', 'Email Notice'), ('website', 'Website Notice'), ('combined', 'Combined Methods')], default='publication', max_length=50)),
                ('notice_deadline', models.DateTimeField(blank=True, null=True)),
                ('objection_deadline', models.DateTimeField(blank=True, null=True)),
                ('opt_out_deadline', models.DateTimeField(blank=True, null=True)),
                ('total_eligible_claimants', models.IntegerField(default=0)),
                ('total_approved_claims', models.IntegerField(default=0)),
                ('total_distributed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Court Approval'), ('approved', 'Court Approved'), ('notice_period', 'Notice Period'), ('distribution', 'Distribution Phase'), ('completed', 'Completed')], default='pending_approval', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mass_claims_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_tracking', to='class_actions.massclaimsrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_settlement_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_actions_settlement_tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
